port: 8070

log:
  logPath: ./logs
  logName: jugglechat-server

mysql:
  user: root
  password: 123456
  address: localhost:3306
  name: im_db
  debug: true

imApiDomain: https://api.juggleim.com # http://127.0.0.1:8082
botConnector:
  domain: <bot-connector url>
  apiKey: <api_key>
